# Generated by Django 6.0.1 on 2026-01-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='clinic_id',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True),
        ),
    ]
