# Generated by Django 5.2.7 on 2026-02-01 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_diagnosis_healthrecord_testresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='extra_info',
            field=models.TextField(blank=True, help_text='Extra information for frontend display'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='extra_info',
            field=models.TextField(blank=True, help_text='Extra information for frontend display'),
        ),
    ]
