# Generated by Django 5.2.7 on 2026-03-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_appointment_child_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(blank=True, db_index=True, help_text='Type of appointment, e.g. General, Antenatal, Eyes', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_method',
            field=models.CharField(blank=True, db_index=True, help_text='Payment method: cash or transfer', max_length=16, null=True),
        ),
    ]
