# Generated by Django 5.2.7 on 2026-04-06 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_appointment_appointment_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendedPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('clinic_id', models.CharField(max_length=32)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sex', models.CharField(max_length=16)),
                ('attended_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'appointments_attendedpatient',
                'ordering': ['-attended_at'],
            },
        ),
    ]
