# Generated by Django 5.2.7 on 2026-04-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_attendedpatient'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendedpatient',
            name='payment_method',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
