# Generated by Django 5.2.7 on 2026-04-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_attendedpatient_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendedpatient',
            name='appointment_type',
            field=models.CharField(blank=True, help_text='Type of appointment, e.g. General, Antenatal, Eyes', max_length=32, null=True),
        ),
    ]
