# Generated by Django 5.2.7 on 2026-04-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0011_attendedpatient_appointment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendedpatient',
            name='payment_type',
            field=models.CharField(blank=True, help_text='Type of payment, e.g. full, partial, insurance', max_length=32, null=True),
        ),
    ]
