# Generated by Django 5.2.7 on 2026-04-26 13:43

import appointments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0012_attendedpatient_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='date',
            field=models.DateField(default=appointments.models.get_today),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='date',
            field=models.DateField(default=appointments.models.get_today),
        ),
    ]
