# Generated by Django 6.0.1 on 2026-01-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='clinic_id',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
