# Generated by Django 6.0.1 on 2026-01-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_patientprofile_first_name_patientprofile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='othername',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
