# Generated by Django 6.0.1 on 2026-01-31 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_patientprofile_othername'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='blood_pressure',
            field=models.CharField(blank=True, help_text='e.g. 120/80 mmHg', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='cholesterol_level',
            field=models.CharField(blank=True, help_text='e.g. 180 mg/dL', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='cm', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='sugar_level',
            field=models.CharField(blank=True, help_text='e.g. 90 mg/dL', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='kg', max_digits=6, null=True),
        ),
    ]
