# Generated by Django 5.2.7 on 2026-03-07 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_patientprofile_blood_pressure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_link', to='users.patientprofile')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Child Account',
                'verbose_name_plural': 'Child Accounts',
                'db_table': 'child_account',
            },
        ),
    ]
