# Generated by Django 5.2.7 on 2026-03-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_patientprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='childaccount',
            name='bloodgroup',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
