# Generated by Django 5.2.7 on 2026-03-08 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_childaccount_bloodgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='users.childaccount')),
            ],
            options={
                'verbose_name': 'Child Appointment',
                'verbose_name_plural': 'Child Appointments',
                'db_table': 'child_appointment',
            },
        ),
    ]
