# Generated by Django 5.2.7 on 2026-06-07 04:10

from django.db import migrations, connection


def fix_fk_constraints(apps, schema_editor):
    """
    Clean up corrupted data that violates FK constraints.
    This handles cases where PatientProfile has NULL user but is referenced by ChildAccount.
    """
    if schema_editor.connection.vendor == 'sqlite':
        # SQLite specific: temporarily disable FK constraint checks
        with connection.cursor() as cursor:
            cursor.execute('PRAGMA foreign_keys = OFF')
    
    # Get the models
    ChildAccount = apps.get_model('users', 'ChildAccount')
    PatientProfile = apps.get_model('users', 'PatientProfile')
    
    # Step 1: Find and delete ChildAccounts that reference PatientProfiles with NULL user
    bad_child_accounts = []
    for ca in ChildAccount.objects.all():
        if ca.child_profile and ca.child_profile.user is None:
            bad_child_accounts.append(ca.id)
    
    if bad_child_accounts:
        print(f"Deleting {len(bad_child_accounts)} ChildAccounts with NULL user references...")
        ChildAccount.objects.filter(id__in=bad_child_accounts).delete()
    
    # Step 2: Find and delete PatientProfiles with NULL user
    null_user_profiles = PatientProfile.objects.filter(user__isnull=True)
    if null_user_profiles.exists():
        count = null_user_profiles.count()
        print(f"Deleting {count} PatientProfiles with NULL user field...")
        null_user_profiles.delete()
    
    if schema_editor.connection.vendor == 'sqlite':
        # Re-enable FK constraint checks
        with connection.cursor() as cursor:
            cursor.execute('PRAGMA foreign_keys = ON')


def reverse_fix(apps, schema_editor):
    """Reverse operation - this is destructive so we don't really reverse it."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_patientprofile_profile_picture'),
    ]

    operations = [
        migrations.RunPython(fix_fk_constraints, reverse_fix),
    ]
