# Generated by Django 5.2.7 on 2026-06-07 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_patientprofile_user'),
    ]

    operations = [
        # First delete ChildAccounts that reference PatientProfiles with NULL user
        migrations.RunSQL(
            sql="""
            DELETE FROM users_child_account 
            WHERE child_profile_id IN (
                SELECT id FROM users_patient_profile WHERE user_id IS NULL
            );
            """,
            reverse_sql="-- This operation cannot be reversed as data is permanently deleted"
        ),
        # Then delete PatientProfiles with NULL user
        migrations.RunSQL(
            sql="""
            DELETE FROM users_patient_profile 
            WHERE user_id IS NULL;
            """,
            reverse_sql="-- This operation cannot be reversed as data is permanently deleted"
        ),
    ]
