# Generated by Django 5.2.7 on 2026-06-07 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_fix_patient_profile_corruption_sql'),
    ]

    operations = [
        # CRITICAL: Clean up corrupted PatientProfiles with NULL user field
        # This WILL run and MUST succeed
        migrations.RunSQL(
            sql="""
            -- Delete ChildAccounts referencing PatientProfiles with NULL user first
            DELETE FROM child_account 
            WHERE child_profile_id IN (
                SELECT id FROM patient_profile WHERE user_id IS NULL
            );
            
            -- Delete PatientProfiles with NULL user
            DELETE FROM patient_profile 
            WHERE user_id IS NULL;
            """,
            reverse_sql="-- Cleanup is irreversible"
        ),
    ]
